#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

# NOTE: If you are not storing files in ~/projects/ Then change it here!
proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
[ ! -d ~/projects/$proj_name ] && mkdir -p ~/projects/$proj_name
add2virtualenv ~/projects/$proj_name
cd ~/projects/$proj_name